// Code generated by protoc-gen-go.
// source: source/zooko.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Transaction struct {
	Id                 *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Branch             *int32   `protobuf:"varint,2,req,name=branch" json:"branch,omitempty"`
	VerificationHashes [][]byte `protobuf:"bytes,3,rep,name=verification_hashes" json:"verification_hashes,omitempty"`
	Raw                []byte   `protobuf:"bytes,4,req,name=raw" json:"raw,omitempty"`
	BlockId            *string  `protobuf:"bytes,5,req,name=block_id" json:"block_id,omitempty"`
	Value              *int32   `protobuf:"varint,6,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}

func (m *Transaction) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Transaction) GetBranch() int32 {
	if m != nil && m.Branch != nil {
		return *m.Branch
	}
	return 0
}

func (m *Transaction) GetVerificationHashes() [][]byte {
	if m != nil {
		return m.VerificationHashes
	}
	return nil
}

func (m *Transaction) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Transaction) GetBlockId() string {
	if m != nil && m.BlockId != nil {
		return *m.BlockId
	}
	return ""
}

func (m *Transaction) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ResolvedName struct {
	Found            *bool          `protobuf:"varint,1,req,name=found" json:"found,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ResolvedName) Reset()         { *m = ResolvedName{} }
func (m *ResolvedName) String() string { return proto.CompactTextString(m) }
func (*ResolvedName) ProtoMessage()    {}

func (m *ResolvedName) GetFound() bool {
	if m != nil && m.Found != nil {
		return *m.Found
	}
	return false
}

func (m *ResolvedName) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
}
